task2_review
wooz1ewu/ITechArt_JavaScript pull request #2
Opened 2021-06-17 14:27 UTC by wooz1ewu

2021-06-18 16:01 UTC, k-krasilnikova requested changes

2021-06-18 18:52 UTC, wooz1ewu commented on task2/script/script.js
> +  return callback.bind(context);
Does callback has to be an arrow function or this is the exact error I should have found? Should I rewrite it to common function?

2021-06-18 19:26 UTC, wooz1ewu commented
Nevermind, I found more or less acceptable solution to my problem, but codepen and jsbin are refusing to run this code. But I tested it in both Edge and Chrome browsers, it works. So weird..

2021-06-21 11:26 UTC, k-krasilnikova approved these changes

2021-06-21 11:31 UTC, merged